#!/bin/bash

list='
src/C_data_collectors_src/data_collect_nv_power.c
src/aux/extra
src/modules/nv_power
src/modules/nv_temperature
src/modules/power
src/unit_test
'

for i in $list; do
   cp -p $i /home1/00770/milfeld/REMORA/KM_vista/$i
done
