#!/bin/bash
#
#========================================================================
# HEADER
#========================================================================
#% DESCRIPTION
#% cpu
#%
#% DO NOT call this script directly. This is called by REMORA
#%
#========================================================================
#- IMPLEMENTATION
#-      version     REMORA 1.6
#-      authors     Carlos Rosales (carlos@tacc.utexas.edu)
#-                  Antonio Gomez  (agomez@tacc.utexas.edu)
#-      license     MIT
#========================================================================

# All the functions take three arguments:
#  1.- The name of the node where this function is running
#  2.- The full path where the output will be stored/read
#  3.- The full path to an optional temporary storage location

init_module_cpu()
{
  REMORA_NODE=$1; REMORA_OUTDIR=$2; REMORA_TMPDIR=$3
  rm -f $REMORA_TMPDIR/cpu*
  if [ "$REMORA_MODE" == "MONITOR" ]; then
	REMORA_MASTER=`head -n 1 $REMORA_OUTDIR/remora_nodes.txt`
	if [ "$REMORA_NODE" == "$REMORA_MASTER" ]; then
		printf "%10s %9s " "#CPU_MAX_%" "CPU_MIN_%" >> $REMORA_TMPDIR/.monitor
	fi
  fi
}

collect_data_cpu()
{
  REMORA_NODE=$1; REMORA_OUTDIR=$2; REMORA_TMPDIR=$3
  # Get CPU utilization
  # We use mpstat (installed with Remora) to collect this data
  mpstat -P ALL 1 1 | grep Average| awk '
  {
    for (i=2; i<=NF; i++)  {
        a[NR,i] = $i
    }
  }
  NF>p { p = NF }
  END {
    print " %time " systime();
    for(j=3; j<=p; j++) {
        if (j==2 || j==3 || j==5 || j==11) {
            str=""
        for(i=1; i<=NR; i++){
                if (i!=2) {
            str=str" "a[i,j];
            }
        }
        print str
        }
    }
  }' >> $REMORA_TMPDIR/cpu_${REMORA_NODE}.txt
}


# This function might perform some processing on the data.
# If nothing needs to be done, it can be empty (but declared)
process_data_cpu()
{
  :
}

monitor_data_cpu()
{
    REMORA_NODE=$1; REMORA_OUTDIR=$2; REMORA_TMPDIR=$3
	REMORA_MASTER=`head -n 1 $REMORA_OUTDIR/remora_nodes.txt`
    if [ "$REMORA_NODE" == "$REMORA_MASTER" ]; then
        avg_cpu=0; max_cpu=0; min_cpu=200
        for NODE in `cat $REMORA_OUTDIR/remora_nodes.txt`
        do 
			if [ -r $REMORA_TMPDIR/cpu_$NODE.txt ]; then 
            	COMMAND="tail -n 3 $REMORA_TMPDIR/cpu_$NODE.txt"
            	avg_cpu=`ssh $NODE $COMMAND | head -n 1`
				avg_cpu=`echo $avg_cpu | awk '{for(i=1;i<NF;i++)avg+=$i} END {print avg/(NF-1)}'`
            	if [ $(echo "$avg_cpu > $max_cpu" | bc) -eq 1 ]; then max_cpu=$avg_cpu; fi
				if [ $(echo "$avg_cpu < $min_cpu" | bc) -eq 1 ]; then min_cpu=$avg_cpu; fi
			fi
        done
        echo "$max_cpu $min_cpu" >> $REMORA_OUTDIR/monitor_cpu.txt 
		#echo "" >> $REMORA_OUTDIR/monitor.txt
		#echo "====================================" >> $REMORA_OUTDIR/monitor.txt
		printf "\n %9.1f%8.1f " $max_cpu $min_cpu >> $REMORA_TMPDIR/.monitor
    fi  
}

finalize_module_cpu()
{
  :
}
