#!/bin/sh
#
#========================================================================
# HEADER
#========================================================================
#% DESCRIPTION
#% ib
#%
#% DO NOT call this script directly. This is called by REMORA
#%
#========================================================================
#- IMPLEMENTATION
#-      version     REMORA 1.4
#-      authors     Carlos Rosales (carlos@tacc.utexas.edu)
#-                  Antonio Gomez  (agomez@tacc.utexas.edu)
#-      license     MIT
#
#========================================================================
#  HISTORY
#       2015/12/08: Initial commit
#========================================================================

# All the functions take two arguments:
#  1.- The name of the node where this function is running
#  2.- The full path where the output will be stored/read
init_module_ib()
{
    packets=`cat /sys/class/infiniband/mlx4_0/ports/1/counters/port_xmit_packets`
}

collect_data_ib()
{
    TIMESTAMP=`date +%s`
    newpackets=`cat /sys/class/infiniband/mlx4_0/ports/1/counters/port_xmit_packets`
    printf "%d %10d\n" $TIMESTAMP $((newpackets-packets)) >> $2/ib_xmit_packets-$1.txt
    packets=$newpackets
}
# This function might perform some processing on the data.
# If nothing needs to be done, it can be empty (but declared)
process_data_ib()
{
  :
}

finalize_module_ib()
{
  :
}
