#!/bin/sh
#
#========================================================================
# HEADER
#========================================================================
#% DESCRIPTION
#% mpi
#%
#% DO NOT call this script directly. This is called by REMORA
#%
#========================================================================
#- IMPLEMENTATION
#-      version     REMORA 1.7
#-      authors     Carlos Rosales (carlos@tacc.utexas.edu)
#-                  Antonio Gomez  (agomez@tacc.utexas.edu)
#-      license     MIT
#========================================================================

# All the functions take three arguments:
#  1.- The name of the node where this function is running
#  2.- The full path where the output will be stored/read
#  3.- The full path to an optional temporary storage location

init_module_impi()
{
  REMORA_NODE=$1; REMORA_OUTDIR=$2; REMORA_TMPDIR=$3

  REMORA_MASTER=`head -n 1 $REMORA_OUTDIR/remora_nodes.txt`
  if [ "$REMORA_NODE" == "$REMORA_MASTER" ]; then
      echo "export I_MPI_STATS=ipm" >> $REMORA_OUTDIR/remora_env.txt
      echo "export I_MPI_STATS_FILE=mpi_data.txt" >> $REMORA_OUTDIR/remora_env.txt
  fi
}

collect_data_impi()
{
  :
}

# This function might perform some processing on the data.
# If nothing needs to be done, it can be empty (but declared)
process_data_impi()
{
  :
}

monitor_data_impi()
{
  :
}

finalize_module_impi()
{
  REMORA_NODE=$1; REMORA_OUTDIR=$2; REMORA_TMPDIR=$3
  source $REMORA_OUTDIR/remora_env.txt
  REMORA_MASTER=`head -n 1 $REMORA_OUTDIR/remora_nodes.txt`
  if [ "$REMORA_NODE" == "$REMORA_MASTER" ]; then
	if [ "$REMORA_MODE" == "FULL" ] || [ "$REMORA_MODE" == "MONITOR" ]; then
        cd $REMORA_OUTDIR/..
        # Check for mpiP output in case code was not MPI based
        fileNum=$( ls -ltr mpi_data.txt )
        if [ -n "$fileNum" ]; then
            outfile=mpi_data.txt
            mpiNum=$( grep "mpi_tasks" $outfile | awk '{print $7}' )
            nodeNum=$( grep "mpi_tasks" $outfile | awk '{print $9}' )
            usrTime=$( grep "# user" $outfile | awk '{print $6}' )
            sysTime=$(grep "# system" $outfile | awk '{print $6}' )
            mpiTime=$(grep "# mpi" $outfile | awk '{print $6}' )
            mpiFrac=$( echo "scale=4; 100.0 * $mpiTime / ( $usrTime + $sysTime +$mpiTime )" | bc ) 
            echo "Number of Nodes     : $nodeNum"    >  $REMORA_OUTDIR/mpi_info.txt
            echo "Number of MPI Tasks : $mpiNum"     >> $REMORA_OUTDIR/mpi_info.txt
            echo "Communication Time  : $mpiFrac %"  >> $REMORA_OUTDIR/mpi_info.txt
            mv $outfile $REMORA_OUTDIR/mpi_data.txt
	  fi
    fi
  fi
}
