#!/bin/bash
#
#========================================================================
# HEADER
#========================================================================
#% DESCRIPTION
#% lnet
#%
#% DO NOT call this script directly. This is called by REMORA
#%
#========================================================================
#- IMPLEMENTATION
#-      version     REMORA 1.5
#-      authors     Carlos Rosales (carlos@tacc.utexas.edu)
#-                  Antonio Gomez  (agomez@tacc.utexas.edu)
#-      license     MIT
#========================================================================

# All the functions take three arguments:
#  1.- The name of the node where this function is running
#  2.- The full path where the output will be stored/read
#  3.- The full path to an optional temporary storage location

init_module_lnet()
{
    REMORA_NODE=$1; REMORA_OUTDIR=$2; REMORA_TMPDIR=$3
    if [ "$REMORA_MODE" == "FULL" ] || [ "$REMORA_MODE" == "MONITOR" ]; then
		if [ "$REMORA_LUSTRE" == "1" ]; then
        #Lustre counters
        printf "%-17s %-17s %-17s %-17s %-17s %-17s %-17s %-17s %-17s %-17s %-17s %-17s\n" "time" "msgs_alloc" "msgs_max" "errors" "send_count" "recv_count" "route_count" "drop_count" "send_length" "recv_length" "route_length" "drop_length" > $REMORA_TMPDIR/lnet_counters_${REMORA_NODE}.txt
		fi 
   fi
}

collect_data_lnet()
{
    REMORA_NODE=$1; REMORA_OUTDIR=$2; REMORA_TMPDIR=$3
    if [ "$REMORA_MODE" == "FULL" ] || [ "$REMORA_MODE" == "MONITOR" ]; then
		if [ "$REMORA_LUSTRE" == "1" ]; then
        local TIMESTAMP=`date +%s`
        local lnetstats=`cat /proc/sys/lnet/stats`
        printf "%-17d %-17d %-17d %-17d %-17d %-17d %-17d %-17d %-17d %-17d %-17d %-17d\n" $TIMESTAMP $lnetstats >> $REMORA_TMPDIR/lnet_counters_${REMORA_NODE}.txt
		fi
    fi
}

process_data_lnet()
{
  :
}

monitor_lnet()
{
  :
}

finalize_module_lnet()
{
  :
}
