#!/bin/bash
#
#========================================================================
# HEADER
#========================================================================
#% DESCRIPTION
#% modules_utils
#%
#% DO NOT call this script directly. This is called by REMORA
#%
#========================================================================
#- IMPLEMENTATION
#-      version     REMORA 1.8.4
#-      authors     Carlos Rosales (carlos@tacc.utexas.edu)
#-                  Antonio Gomez  (agomez@tacc.utexas.edu)
#-      license     MIT
#========================================================================

#Call the init_module function of each active module
remora_configure_modules()
{
    source $REMORA_BIN/aux/extra
    source $REMORA_BIN/modules/modules_utils
    remora_read_active_modules

    for MODULE in "${REMORA_MODULES[@]}"
    do
        if [[ "$REMORA_VERBOSE" == "1" ]]; then
            echo init_module_$MODULE $1 $2 $3 
        fi
        init_module_$MODULE $1 $2 $3
    done
}

# Call the monitor_module function of each active module
remora_monitor_modules()
{
    local NODE=$1
    local OUTDIR=$2
    local TMPDIR=$3
    shift 3
    REMORA_MODULES=("${@}")

    for MODULE in "${REMORA_MODULES[@]}"
    do  
        if [[ "$REMORA_VERBOSE" == "1" ]]; then
            echo "monitor_data_$MODULE $NODE $OUTDIR $TMPDIR"
        fi  
        monitor_data_$MODULE $NODE $OUTDIR $TMPDIR
    done
}

#Call the c llect_data_module function of each active module
remora_execute_modules()
{
    local NODE=$1
    local OUTDIR=$2
    local TMPDIR=$3
    shift 3
    REMORA_MODULES=("${@}")

    for MODULE in "${REMORA_MODULES[@]}"
    do
        if [[ "$REMORA_VERBOSE" == "1" ]]; then
            echo "collect_data_$MODULE $NODE $OUTDIR $TMPDIR"
        fi
        collect_data_$MODULE $NODE $OUTDIR $TMPDIR
    done
}

#Call the finalize_module function of each active module
remora_finalize_modules()
{
    for MODULE in "${REMORA_MODULES[@]}"
    do
        if [[ "$REMORA_VERBOSE" == "1" ]]; then
            echo finalize_module_$MODULE $1 $2 $3 
        fi
        finalize_module_$MODULE $1 $2 $3
    done
}

# Here we just make sure the visible monitor file is updated all at one time
remora_monitor_summary()
{
	REMORA_MASTER=`head -n 1 $REMORA_OUTDIR/remora_nodes.txt`
	if [[ "$1" == "$REMORA_MASTER" ]]; then
		tail -n 1 $REMORA_TMPDIR/.monitor >> $REMORA_OUTDIR/monitor.txt
		echo "" >> $REMORA_OUTDIR/monitor.txt
	fi
}

