#!/bin/sh
#
#========================================================================
# HEADER
#========================================================================
#% DESCRIPTION
#% modules_utils
#%
#% DO NOT call this script directly. This is called by REMORA
#%
#========================================================================
#- IMPLEMENTATION
#-      version     REMORA 1.4
#-      authors     Carlos Rosales (carlos@tacc.utexas.edu)
#-                  Antonio Gomez  (agomez@tacc.utexas.edu)
#-      license     MIT
#
#========================================================================
#  HISTORY
#       2015/12/08: Initial commit
#========================================================================

remora_read_active_modules()
{
    fileItemString=$(cat $REMORA_BIN/config/modules | tr "\n" " ")

    REMORA_MODULES=($fileItemString)
    REMORA_ACTIVE_MODS=${#REMORA_MODULES[@]}
    for MODULE in "${REMORA_MODULES[@]}"
    do
      source $REMORA_BIN/modules/$MODULE
      if [ "$REMORA_VERBOSE" == "1" ]; then
        echo "Module $MODULE is active"
      fi
    done
}

#Call the init_module function of each active module
remora_configure_modules()
{
    for MODULE in "${REMORA_MODULES[@]}"
    do
        if [ "$REMORA_VERBOSE" == "1" ]; then
            echo init_module_$MODULE $1 $2
        fi
        init_module_$MODULE $1 $2
    done
}

#Call the execute_module_function of each active module
remora_execute_modules()
{
    for MODULE in "${REMORA_MODULES[@]}"
    do
        if [ "$REMORA_VERBOSE" == "1" ]; then
            echo collect_data_$MODULE $1 $2
        fi
        collect_data_$MODULE $1 $2
    done
}

#Call the finalize_module function of each active module
remora_finalize_modules()
{
    for MODULE in "${REMORA_MODULES[@]}"
    do
        if [ "$REMORA_VERBOSE" == "1" ]; then
            echo finalize_module_$MODULE $1 $2 $3
        fi
        finalize_module_$MODULE $1 $2 $3
    done
}
