#!/bin/sh
#
#========================================================================
# HEADER
#========================================================================
#% DESCRIPTION
#% network
#%
#% DO NOT call this script directly. This is called by REMORA
#%
#========================================================================
#- IMPLEMENTATION
#-      version     REMORA 1.5
#-      authors     Carlos Rosales (carlos@tacc.utexas.edu)
#-                  Antonio Gomez  (agomez@tacc.utexas.edu)
#-      license     MIT
#
#========================================================================
#  HISTORY
#       2015/12/08: Initial commit
#========================================================================

# All the functions take two arguments:
#  1.- The name of the node where this function is running
#  2.- The full path where the output will be stored/read
init_module_network()
{
  :
}

collect_data_network()
{
  :
}

# This function might perform some processing on the data.
# If nothing needs to be done, it can be empty (but declared)
process_data_network()
{
  :
}

finalize_module_network()
{
  REMORA_NODE_ID=$3
  if [ "$REMORA_NODE_ID" -eq "0" ]; then
    local idx=0
    local LID=()
    local NODES=`cat $REMORA_OUTDIR/remora_nodes.txt`
    for NODE in $NODES; do
      LIDCOMMAND="cat /sys/class/infiniband/mlx4_0/ports/1/lid"
      LID[$idx]=`ssh -f $NODE $LIDCOMMAND`
      idx=$((idx+1))
    done
    net_node_cnt=0; for NODE in $NODES; do net_node_cnt=$((net_node_cnt+1)); done
    idx=1
    while [  $idx -lt $net_node_cnt ]; do
      ibtracert ${LID[0]} ${LID[$idx]} >> $REMORA_OUTDIR/trace_network.txt
      echo "_____________" >> $REMORA_OUTDIR/trace_network.txt
      idx=$((idx+1))
    done
  fi
}
