#!/bin/bash

#========================================================================
# HEADER
#========================================================================
#% DESCRIPTION
#% sql_functions
#%
#% This file implements a set of auxiliary functions for managing SQLITE
#% databases
#%
#========================================================================
#- IMPLEMENTATION
#-      version     REMORA 1.7
#-      authors     Carlos Rosales (carlos@tacc.utexas.edu)
#-                  Antonio Gomez  (agomez@tacc.utexas.edu)
#-      license     MIT
#
#========================================================================
#  HISTORY
#       2015/11/29: Initial version
#========================================================================
#

# Location of the REMORA database
REMORADB=$HOME/.remora.db

# Current version of the database
REMORADB_VERSION=1.7

# Function that returns the version stored in the main table of the database
check_db_version()
{
    version=sqlite3 $REMORADB "SELECT version FROM remora_info";
    return version
}

# Function that returns a boolean indicating whether the database already exists
check_db_exists()
{
    if [ -f $REMORADB ];
    then
        return 1
    else
        return 0
    fi
}

# This function creates the database for REMORA. It assumes that the database doesn't
# already exist
# For version 1.6, the tables are the following (this is documented in the REMORA
# repository (https://github.com/TACC/remora):
#
#           remora_info                         jobs
#                                                |
#         ___________________________________________________________________________________
#           |                |                   |               |              |           |
#         numa          memory_usage        cpu_usage       filesystem      network         IB
create_database()
{
    sqlite3 $REMORADB "CREATE TABLE remora_info (version INTEGER, date INTEGER)";
    sqlite3 $REMORADB "INSERT INTO remora_info VALUES ($REMORADB_VERSION, `date +'%s'`)";
    sqlite3 $REMORADB "CREATE TABLE jobs (id INTEGER PRIMARY KEY, time_start INTEGER, time_end INTEGER, commmand TEXT, path TEXT, nodes TEXT)";
    sqlite3 $REMORADB "CREATE TABLE memory_usage (jobid INTEGER, timestamp INTEGER, shmem TEXT, virtual TEXT, resident TEXT, FOREIGN KEY(jobid) REFERENCES jobs(id))";
    sqlite3 $REMORADB "CREATE TABLE cpu_usage (jobid INTEGER, timestamp INTEGER, cpuid INTEGER, usage REAL, FOREIGN KEY(jobid) REFERENCES jobs(id), PRIMARY KEY(timestamp, cpuid))" ;
    sqlite3 $REMORADB "CREATE TABLE filesystem (jobid INTEGER, timestamp INTEGER, fs_name TEXT, requests INTEGER, read INTEGER, write INTEGER, FOREIGN KEY(jobid) REFERENCES jobs(id))";
    # Do we want to have a table with all the nodes in the system?
    # And with all the switches?
    sqlite3 $REMORADB "CREATE TABLE network (jobid INTEGER, FOREIGN KEY(jobid) REFERENCES jobs(id))"; # Finish this
    sqlite3 $REMORADB "CREATE TABLE ib (jobid INTEGER, FOREIGN KEY(jobid) REFERENCES jobs(id))";  # Finish this
    sqlite3 $REMORADB "CREATE TABLE numa_usage (jobid INTEGER, timestamp INTEGER, nodeid INTEGER, local_mem REAL, remote_mem REAL, local_miss REAL, remote_miss REAL, FOREIGN KEY(jobid) REFERENCES jobs(id), PRIMARY KEY(timestamp, nodeid))";
}

# This functions takes as arguments the following values:
#   - job_id
#   - timestamp
#   - shmem
#   - virtual
#   - resident
insert_memory_usage() {
    if [ "$#" -ne 5 ]; then
        print_error " Incorrect syntax: insufficient arguments. "
    else
        sqlite3 $REMORADB "INSERT INTO cpu_usage (job_id, timestamp, shmem, virtual, resident) VALUES ($1, $2, '$3', '$4', $5)";
    fi
}

# This functions takes as arguments the following values:
#   - job_id
#   - timestamp
#   - fs_name
#   - cpu_id
#   - usage
insert_cpu_usage() {
    if [ "$#" -ne 4 ]; then
        print_error " Incorrect syntax: insufficient arguments. "
    else
        sqlite3 $REMORADB "INSERT INTO cpu_usage (job_id, timestamp, cpu_id, usage) VALUES ($1, $2, '$3', '$4')";
    fi
}

# This functions takes as arguments the following values:
#   - job_id
#   - timestamp
#   - filesystem name (HOME, WORK, SCRATCH,...)
#   - requests
insert_fs_usage() {
    if [ "$#" -ne 6 ]; then
        print_error " Incorrect syntax: insufficient arguments. "
    else
        sqlite3 $REMORADB "INSERT INTO filesystem (job_id, timestamp, fsname, requests, read, write) VALUES ($1, $2, '$3', '$4', '$5', '$6')";
    fi
}

# This functions takes as arguments the following values:
#   - job_id
#   - timestamp
#   - node_id (name of the node)
#   - local_mem (mem used in local memory)
#   - remote_mem (mem used in remote remory)
#   - local_miss (misses in local memory)
#   - remote_miss (misses in remote memory)
insert_numa_usage() {
    if [ "$#" -ne 7 ]; then
        print_error " Incorrect syntax: insufficient arguments. "
    else
        sqlite3 $REMORADB "INSERT INTO numa_usage (job_id, timestamp, node_id, local_mem, remote_mem, local_miss, remote_miss) VALUES ($1, $2, '$3', $4, $5, $6, $7)";
    fi
}

# This function will need to be implemented: if the version of the database is older than
# the current version used, some tables will have changed.
update_database()
{
    print_error " This function is not yet implemented. "
}
