#!/bin/bash
#
#========================================================================
# HEADER
#========================================================================
#% SYNOPSIS
#+  remora ./myapp [args]                     (serial applications)
#+  remora ibrun [options] ./myapp [args]     (parallel MPI applications)
#%
#% DESCRIPTION
#% REMORA: REsource MOnitoring for Remote Applications
#%
#% REMORA is an easy to use monitoring tool that allows users to extract
#% valuable information from their jobs:
#%       - CPU usage
#%       - Memory
#%       - IO statistics
#%       - ...
#%
#% It is advisable that he following environmental variables are set:
#%
#% REMORA_PERIOD  - How often statistics are collected.
#%                  Default is 10 seconds.
#%                  Integer values are accepted.
#% REMORA_VERBOSE - Verbose mode will save all information to a file.
#%                  Default is 0 (off).
#%                  Values 0 and 1 are accepted.
#% REMORA_MODE    - How many stats are collected. Possible values:
#%                  - FULL (default): cpu, memory, network, lustre
#%                  - BASIC: cpu, memory
#%
#========================================================================
#- IMPLEMENTATION
#-      version     REMORA 1.7
#-      authors     Carlos Rosales (carlos@tacc.utexas.edu)
#-                  Antonio Gomez  (agomez@tacc.utexas.edu)
#-      license     MIT
#
#========================================================================
#  HISTORY
#       2016/11/10: Added KNL support. New graphs.
#       2016/03/11: Added real-time monitor mode
#	    2016/01/25: Added alternative location for temp files
#       2015/12/09: Implemented a modular design
#       2015/11/21: Removing TACC specific data
#       2015/09/09: Using python parser for file system data
#       2015/08/12: Initial version
#========================================================================
#  CITE REMORA
#       If you use REMORA please cite it, it will help us secure support
#       for further development
#                   REMORA: A Resource Monitoring Tool For Everyone
#                   C. Rosales, A. Gomez-Iglesias, A. Predoehl
#                   HUST2015 November 15-20, 2015, Austin, TX, USA
#                   DOI: 10.1145/2834996.2834999
#
#========================================================================
#
# DEBUG OPTION
#     REMORA_BIN set to workdir with copies of the scripts
#
#========================================================================
# END_OF_HEADER
#========================================================================

# Abort because we will not find any of the functions
# if REMORA_BIN is not defined
if [ -z "$REMORA_BIN" ]; then
    echo "ERROR: REMORA_BIN undefined"
    exit
fi

#Function that tries to exit clean if REMORA is cancelled.
#It finalizes all processes. The main code might continue running though.
exit_clean() {
  $REMORA_BIN/scripts/remora_finalize.sh 0 0
}
#Trap the SIGTERM and SIGINT signals and call exit_clean
trap "exit_clean" TERM SIGINT

#Save the PID of REMORA in case we need it
export REMORA_TOP_PID=$$

SCRIPT_HEADSIZE=$(head -200 ${0} |grep -n "^# END_OF_HEADER" | cut -f1 -d:)
SCRIPT_NAME="$(basename ${0})"

# Parse input and setup data collection
REMORA_OUTDIR=$($REMORA_BIN/scripts/remora_init.sh "$@")
export NODES=`cat $REMORA_OUTDIR/remora_nodes.txt`
source $REMORA_OUTDIR/remora_env.txt

# Output real time results if running in monitor mode
if [ "$REMORA_MODE" == "MONITOR" ]; then
#	touch $REMORA_OUTDIR/monitor.txt
#	tail -f $REMORA_OUTDIR/monitor.txt --pid=$REMORA_TOP_PID &
	echo ""
	echo "REMORA: Running in monitor mode. For real time updates use:"
	echo "        tail -f $REMORA_OUTDIR/monitor.txt"
	echo ""
fi

$REMORA_BIN/scripts/remora_collect.sh "$@"

# Now that we are collecting data in the background
# We can start he actual application
if [ "$REMORA_VERBOSE" == "1" ]; then
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "REMORA: Running command: $@ "
  echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
fi
START=$(date +%s%N)
$@
END=$(date +%s%N)
$REMORA_BIN/scripts/remora_finalize.sh $END $START

